### ISSUE TITLE
over flow menu

### ISSUE THREAD

**Issue by Amratkumar** [NED-University/Smart-Pill-Reminder#11]
overflow menu not working in app

**Comment by Inshal240** [comment]
Overflow menu in which activity? How do I duplicate the issue?

**Comment by Amratkumar** [comment]
activity db viewwer
public boolean onOptionsItemSelected(MenuItem item)

**Comment by Inshal240** [comment]
Overflow button does not appear in GUI. Solved using the actual hardware button.
