### ISSUE TITLE
Database viewer activity

### ISSUE THREAD

**Issue by Inshal240** [NED-University/Smart-Pill-Reminder#8]
Make changes to the DBViewer class to enable viewing of the entire database and editing it.

**Comment by Amratkumar** [comment]
ok

**Comment by Inshal240** [comment]
Settings menu:
Switch to Alarms Table
Switch to Medicine Table
Switch to MedicationHistory Table
Add new item _(Adds a new record in to the currently selected database)_

Context Menu:
Delete Entry _(Remove selected record from the database)_
Duplicate Entry _(Insert another entry into the database, optional)_

**Comment by Amratkumar** [comment]
i was implementing this have you done?
